import type { AnalysisReport } from "@/lib/pipeline";

/**
 * Plain-text summary of the report — suitable for pasting into notes,
 * Slack DMs, or a "what should I work on" todo list.
 *
 * Designed to be useful even without context: starts with the composite
 * and the four dimension scores, then lists the highest-leverage edits.
 */
export function formatTextSummary(report: AnalysisReport): string {
  const { scores } = report;
  const lines: string[] = [];

  lines.push("ATS Resume Analyzer — report summary");
  lines.push("=".repeat(38));
  lines.push("");
  lines.push(`Composite: ${scores.composite}/100`);
  lines.push(`  Keyword match:        ${scores.keyword.score}/100  (30% weight)`);
  lines.push(`  Semantic similarity:  ${scores.semantic.score}/100  (30% weight)`);
  lines.push(`  Hard requirements:    ${scores.hardRequirements.score}/100  (25% weight)`);
  lines.push(`  Parseability:         ${scores.parseability.score}/100  (15% weight)`);
  lines.push("");

  const topMissing = [...scores.keyword.missing]
    .sort((a, b) => b.weight - a.weight)
    .slice(0, 8);
  if (topMissing.length > 0) {
    lines.push("Top missing JD keywords (sorted by weight):");
    for (const k of topMissing) {
      lines.push(
        `  - ${k.surface}  [${k.tier}, weight ${k.weight.toFixed(1)}]`,
      );
    }
    lines.push("");
  }

  const failedReqs = scores.hardRequirements.requirements.filter(
    (r) => !r.passed,
  );
  if (failedReqs.length > 0) {
    lines.push("Hard requirements that did not pass:");
    for (const r of failedReqs) {
      lines.push(`  - ${r.detail}`);
    }
    lines.push("");
  }

  const uncovered = scores.semantic.coverage.filter(
    (c) => c.band === "uncovered",
  );
  if (uncovered.length > 0) {
    lines.push(`Uncovered JD requirements (${uncovered.length}):`);
    for (const c of uncovered.slice(0, 6)) {
      lines.push(`  - ${truncate(c.requirement.text, 100)}`);
    }
    if (uncovered.length > 6) {
      lines.push(`  ... and ${uncovered.length - 6} more`);
    }
    lines.push("");
  }

  if (scores.parseability.issues.length > 0) {
    lines.push("Parseability issues:");
    for (const issue of scores.parseability.issues) {
      lines.push(`  - [${issue.severity}] ${issue.message}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(
    "No real ATS produces a single 'true' score. These are heuristics that highlight specific gaps.",
  );
  lines.push(
    "Generated by https://ats-analyzer-gamma.vercel.app — open source.",
  );

  return lines.join("\n");
}

function truncate(text: string, max: number): string {
  if (text.length <= max) return text;
  return text.slice(0, max - 1).trimEnd() + "…";
}
